import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const PROJECT_REF = "swsmoebtnnyuqtnidmvn";

// Full CSV data from tunee_descriptions.csv — 628 rows
const CSV_ROWS = [
  {pos:1,title:"Roots Horn Anthem",dur:"03:52",desc:"epic Nyabinghi Roots Dub, prophetic, spirit..."},
  {pos:2,title:"Horn Warning Dub",dur:"03:04",desc:"epic Nyabinghi Roots Dub, prophetic, spiri..."},
  {pos:3,title:"Warning Light Anthem",dur:"03:46",desc:"epic Nyabinghi Roots Dub, prophetic, spiri..."},
  {pos:4,title:"Ceremonial Horn Dub",dur:"03:28",desc:"epic Nyabinghi Roots Dub, prophetic, spiri..."},
  {pos:5,title:"Heavy Analog Warning",dur:"04:08",desc:"epic Nyabinghi Roots Dub, prophetic, spiri..."},
  {pos:6,title:"Warning Horn Dub",dur:"03:56",desc:"epic Nyabinghi Roots Dub, prophetic, spiri..."},
  {pos:7,title:"Haitian Queen Night",dur:"02:58",desc:"Sultry dark R&B, slow-burn seductive my..."},
  {pos:8,title:"Bedroom Heat",dur:"03:24",desc:"Sultry dark R&B, slow-burn seductive my..."},
  {pos:9,title:"Deep Desire",dur:"03:13",desc:"Sultry dark R&B, slow and seductive, de..."},
  {pos:10,title:"Late Night Queen",dur:"03:04",desc:"Sultry dark R&B, slow and seductive, de..."},
  {pos:11,title:"Queen's Rhythm",dur:"01:10",desc:"hypnotic Dark Electronic, ominous, dual co..."},
  {pos:12,title:"Voodoo Pulse",dur:"01:32",desc:"hypnotic Dark Electronic, ominous, dual co..."},
  {pos:13,title:"Voodoo Heat",dur:"02:46",desc:"aggressive edgy Trap, dominant, intense,..."},
  {pos:14,title:"Queen's Command",dur:"02:35",desc:"aggressive edgy Trap, dominant, intense,..."},
  {pos:15,title:"Velvet Command",dur:"01:24",desc:"sultry R&B, seductive, breathy female voca..."},
  {pos:16,title:"Midnight Spell",dur:"01:28",desc:"sultry R&B, seductive, breathy female voca..."},
  {pos:17,title:"Bachata Kompa Rise",dur:"03:42",desc:"Triumphant kompa-bachata fusion, Haitia..."},
  {pos:18,title:"Chappadora Victory",dur:"03:58",desc:"Triumphant kompa-bachata fusion, Haitia..."},
  {pos:19,title:"Requinto & Gouyad",dur:"03:52",desc:"upbeat Kompa-Bachata fusion, playful tri..."},
  {pos:20,title:"Chappadora Beat",dur:"04:31",desc:"upbeat Kompa-Bachata fusion, playful tri..."},
  {pos:21,title:"Kompa Bachata Rise",dur:"03:57",desc:"upbeat kompa groove, heavy bassline, sy..."},
  {pos:22,title:"Chappadora Groove",dur:"03:20",desc:"upbeat kompa groove, heavy bassline, sy..."},
  {pos:23,title:"The Storyteller's Bachata",dur:"03:33",desc:"traditional Dominican Bachata with autho..."},
  {pos:24,title:"Chappadora's Karma",dur:"03:27",desc:"Traditional Dominican Bachata with autho..."},
  {pos:25,title:"Karma in Bachata",dur:"03:06",desc:"energetic mambo-infused Dominican bac..."},
  {pos:26,title:"Chappadora Mambo",dur:"03:31",desc:"energetic mambo-infused Dominican bac..."},
  {pos:27,title:"Requinto Karma",dur:"03:24",desc:"Classic Requinto Focus - emphasizing aut..."},
  {pos:28,title:"Chappadora Mambo",dur:"03:06",desc:"Classic Requinto Focus - emphasizing aut..."},
  {pos:29,title:"Three-Stranded Cord",dur:"04:14",desc:"gentle slow tempo meditative worship ball..."},
  {pos:30,title:"Two Are Better Than One",dur:"04:19",desc:"gentle slow tempo meditative worship ball..."},
  {pos:31,title:"Three-Stranded Cord",dur:"04:22",desc:"meditative, reverent Worship Ballad, gentl..."},
  {pos:32,title:"Two Are Better Than One",dur:"04:00",desc:"meditative, reverent Worship Ballad, gentl..."},
  {pos:33,title:"Three-Stranded Cord V5",dur:"04:35",desc:"meditative pace, intertwined guitar and pi..."},
  {pos:34,title:"Three-Stranded Cord V4",dur:"04:35",desc:"meditative pace, intertwined guitar and pi..."},
  {pos:35,title:"Bachata by the Sea",dur:"04:26",desc:"triumphant joyful classic Dominican Bach..."},
  {pos:36,title:"Chappadora Karma",dur:"03:55",desc:"triumphant joyful classic Dominican Bach..."},
  {pos:37,title:"Bachata by the Sea",dur:"04:10",desc:"triumphant joyful classic Dominican Bachata, sm..."},
  {pos:38,title:"Chappadora Karma",dur:"04:01",desc:"triumphant joyful classic Dominican Bachata, sm..."},
  {pos:39,title:"Bachata by the Sea",dur:"04:05",desc:"joyful triumphant classic Dominican Bach..."},
  {pos:40,title:"Chappadora Karma",dur:"03:56",desc:"joyful triumphant classic Dominican Bach..."},
  {pos:41,title:"Bachata Goodbye",dur:"03:40",desc:"upbeat bachata, bongos, güira, nylon-stri..."},
  {pos:42,title:"Chappadora Karma",dur:"03:46",desc:"upbeat bachata, bongos, güira, nylon-stri..."},
  {pos:43,title:"Three-Stranded Cord",dur:"04:19",desc:"meditative pace, intertwined guitar and pi..."},
  {pos:44,title:"Two Are Better Than One",dur:"04:18",desc:"meditative pace, intertwined guitar and pi..."},
  {pos:45,title:"Three-Stranded Cord",dur:"04:43",desc:"meditative worship ballad, gentle, revere..."},
  {pos:46,title:"Two Are Better Than One",dur:"04:04",desc:"meditative worship ballad, gentle, revere..."},
  {pos:47,title:"Three-Stranded Cord",dur:"04:42",desc:"meditative worship ballad, gentle, revere..."},
  {pos:48,title:"Two Are Better Than One",dur:"04:34",desc:"meditative worship ballad, gentle, revere..."},
  {pos:49,title:"Karma en la calle lateral",dur:"03:23",desc:"joyful festive Bachata, uplifting, triumpha..."},
  {pos:50,title:"Chappadora, el final feliz",dur:"03:00",desc:"joyful festive Bachata, uplifting, triumpha..."},
  {pos:51,title:"Calle Lateral",dur:"02:59",desc:"urban-infused Modern Bachata, dramati..."},
  {pos:52,title:"Chappadora y el Karma",dur:"03:08",desc:"urban-infused Modern Bachata, dramati..."},
  {pos:53,title:"Bachata de la Calle Lateral",dur:"02:48",desc:"romantic classic bachata, soft acoustic..."},
  {pos:54,title:"Chappadora y el Karma",dur:"02:55",desc:"romantic classic bachata, soft acoustic..."},
  {pos:55,title:"Break the Vessel",dur:"04:22",desc:"contemplative, reverent Ambient Spiritu..."},
  {pos:56,title:"The Water I Carried",dur:"04:40",desc:"contemplative, reverent Ambient Spiritu..."},
  {pos:57,title:"Break the Vessel",dur:"04:14",desc:"soulful, confessional Acoustic Folk Gospe..."},
  {pos:58,title:"The Water I Carried",dur:"04:40",desc:"soulful, confessional Acoustic Folk Gospe..."},
  {pos:59,title:"Break the Vessel",dur:"05:03",desc:"meditative, solemn Roots Reggae with sl..."},
  {pos:60,title:"The Water I Carried",dur:"04:38",desc:"meditative, solemn Roots Reggae with sl..."},
  {pos:61,title:"Mercy Stone Anthem",dur:"03:46",desc:"epic, solemn Cinematic Orchestral with s..."},
  {pos:62,title:"Eden to Calvary",dur:"03:58",desc:"epic, solemn Cinematic Orchestral with s..."},
  {pos:63,title:"Truth at Dawn",dur:"03:47",desc:"haunting ethereal choral build starting w..."},
  {pos:64,title:"Mercy Stone Rising",dur:"03:21",desc:"haunting ethereal choral build starting w..."},
  {pos:65,title:"Mercy Stone and Lies",dur:"04:07",desc:"melancholic, solemn Dark Folk with finge..."},
  {pos:66,title:"The Poison Tree's Shadow",dur:"04:14",desc:"melancholic, solemn Dark Folk with finge..."},
  {pos:67,title:"Fruit and Fire",dur:"02:31",desc:"Haitian kompa style at 110-120 BPM with e..."},
  {pos:68,title:"Poison Tree Kompa",dur:"02:25",desc:"Haitian kompa style at 110-120 BPM with e..."},
  {pos:69,title:"Bitter Fruit Serenade",dur:"03:39",desc:"Traditional Dominican Bachata at 120-130..."},
  {pos:70,title:"Poison Tree Bachata",dur:"03:35",desc:"Traditional Dominican Bachata at 120-130..."},
  {pos:71,title:"Bitter Fruit Serenade",dur:"04:10",desc:"Traditional Dominican Bachata at 120-130..."},
  {pos:72,title:"Poison Tree Bachata",dur:"03:43",desc:"Traditional Dominican Bachata at 120-130..."},
  {pos:73,title:"Haiti Hear This",dur:"02:58",desc:"Haitian kompa style at 110-120 BPM with e..."},
  {pos:74,title:"Poison Tree Kompa",dur:"02:44",desc:"Haitian kompa style at 110-120 BPM with e..."},
  {pos:75,title:"Redeem the Root",dur:"03:36",desc:"uplifting Modern Christian Reggae, hopef..."},
  {pos:76,title:"Poison Tree Mercy",dur:"03:54",desc:"uplifting Modern Christian Reggae, hopef..."},
  {pos:77,title:"Mercy at Dawn",dur:"04:14",desc:"solemn Gospel Ballad, reverent, melanch..."},
  {pos:78,title:"Fruit of the Poison Tree",dur:"03:42",desc:"solemn Gospel Ballad, reverent, melanch..."},
  {pos:79,title:"Modern Prophetic Groove",dur:"04:48",desc:"reverent, meditative Roots Reggae with c..."},
  {pos:80,title:"Mercy's Stone Reverence",dur:"03:48",desc:"reverent, meditative Roots Reggae with c..."},
  {pos:81,title:"Prophet's Stillness",dur:"03:46",desc:"solemn, meditative Roots Reggae with ce..."},
  {pos:82,title:"Mercy's Stone",dur:"03:50",desc:"solemn, meditative Roots Reggae with ce..."},
  {pos:83,title:"Rising Trust",dur:"03:48",desc:"uplifting, hopeful Roots Reggae with cere..."},
  {pos:84,title:"Mercy's Stone",dur:"02:54",desc:"uplifting, hopeful Roots Reggae with cere..."},
  {pos:85,title:"Mercy's Stone",dur:"03:20",desc:"English roots reggae, meditative, slow one..."},
  {pos:86,title:"Steady Reverence",dur:"03:22",desc:"English roots reggae, meditative, slow one..."},
  {pos:87,title:"Mercy's Steadfast Stone",dur:"02:50",desc:"Modern worship song with reflective dyna..."},
  {pos:88,title:"Flesh Fails, Grace Holds",dur:"03:16",desc:"reverent Modern Worship with atmospheri..."},
  {pos:89,title:"Flesh Fails, Grace Holds",dur:"03:41",desc:"reverent Modern Worship with atmospheri..."},
  {pos:90,title:"Steady Mercy Pulse",dur:"03:51",desc:"reverent Modern Worship with atmospheri..."},
  {pos:91,title:"Mercy's Steadfast Stone",dur:"03:47",desc:"Subtle Atmospheric Build - starts with soft..."},
  {pos:92,title:"Flesh Will Fail",dur:"04:05",desc:"Subtle Atmospheric Build - starts with soft..."},
  {pos:93,title:"Steady Kompa, Steady Faith",dur:"03:24",desc:"traditional Haitian Kompa groove with ba..."},
  {pos:94,title:"Flesh Fails, Mercy Holds",dur:"03:38",desc:"traditional Haitian Kompa groove with ba..."},
  {pos:95,title:"Flesh Fails, Rhythm Holds",dur:"03:32",desc:"traditional Haitian Kompa groove with stea..."},
  {pos:96,title:"Steady Drum, Steady Faith",dur:"02:59",desc:"traditional Haitian Kompa groove with stea..."},
  {pos:97,title:"Flesh Will Fail",dur:"03:43",desc:"traditional Haitian Kompa, reflective, intim..."},
  {pos:98,title:"Horn and Mercy",dur:"03:14",desc:"traditional Haitian Kompa, reflective, intim..."},
  {pos:99,title:"Trust Not in Flesh",dur:"03:19",desc:"19th-century Christian hymn style (Fanny..."},
  {pos:100,title:"The Arm of Flesh Will Fail You",dur:"02:46",desc:"19th-century Christian hymn style (Fanny..."},
  {pos:101,title:"Confianza en la Piedra",dur:"02:52",desc:"Dominican bachata, melancholic solemn..."},
  {pos:102,title:"El Brazo de Carne Fallará",dur:"03:01",desc:"Dominican bachata, melancholic solemn..."},
  {pos:103,title:"Brazo de Carne, Ritmo Profun...",dur:"02:50",desc:"Dominican bachata, solemn spiritual, mel..."},
  {pos:104,title:"Ritmo de la Carne y la Fe",dur:"02:55",desc:"Dominican bachata, solemn spiritual, mel..."},
  {pos:105,title:"Confianza en la Piedra",dur:"03:16",desc:"introspective spiritual Dominican bachata..."},
  {pos:106,title:"El Brazo de Carne Fallará",dur:"03:07",desc:"introspective spiritual Dominican bachata..."},
  {pos:107,title:"Requinto and Mercy",dur:"03:04",desc:"Traditional Dominican Bachata, reflective..."},
  {pos:108,title:"Flesh Fails, Grace Stays",dur:"02:48",desc:"Traditional Dominican Bachata, reflective..."},
  {pos:109,title:"Drum Call to Faith",dur:"03:43",desc:"spiritual ceremonial Haitian Racine, prop..."},
  {pos:110,title:"Bra Lachas Rising",dur:"03:17",desc:"spiritual ceremonial Haitian Racine, prop..."},
  {pos:111,title:"Sacred Silence and Drum",dur:"03:49",desc:"spiritual ceremonial Haitian Racine, prop..."},
  {pos:112,title:"Prophet's Voice Courtyard",dur:"03:09",desc:"spiritual ceremonial Haitian Racine, prop..."},
  {pos:113,title:"Faith in the Drum",dur:"04:07",desc:"authentic Haitian Racine devotional, spirit..."},
  {pos:114,title:"Tanbou Calling",dur:"02:57",desc:"authentic Haitian Racine devotional, spirit..."},
  {pos:115,title:"Faith in the Trembling Air",dur:"03:33",desc:"solemn, hypnotic devotional Reggae, Hait..."},
  {pos:116,title:"Prophet's Sacred Silence",dur:"02:55",desc:"solemn, hypnotic devotional Reggae, Hait..."},
  {pos:117,title:"Prophet's Steady Cry",dur:"04:02",desc:"devotional Reggae, solemn, hypnotic, Haiti..."},
  {pos:118,title:"Faith in the Storm",dur:"03:19",desc:"devotional Reggae, solemn, hypnotic, Haiti..."},
  {pos:119,title:"Prophet God's Call",dur:"03:08",desc:"devotional Reggae, solemn, hypnotic, Haiti..."},
  {pos:120,title:"Steady Faith Groove",dur:"03:50",desc:"devotional Reggae, solemn, hypnotic, Haiti..."},
  {pos:121,title:"Mi Confianza Está Solo en Dios",dur:"03:09",desc:"Afro-Dominican devotional fusion, spiritual..."},
  {pos:122,title:"El Brazo Que Falla",dur:"03:14",desc:"Afro-Dominican devotional fusion, spiritual..."},
  {pos:123,title:"No Confío en Carne",dur:"02:41",desc:"devotional reggae, roots rhythm, upright b..."},
  {pos:124,title:"El Brazo de Carne Fallará",dur:"02:46",desc:"devotional reggae, roots rhythm, upright b..."},
  {pos:125,title:"Tambora y Fe",dur:"03:48",desc:"Afro-Dominican devotional fusion, reveren..."},
  {pos:126,title:"El Brazo Que Falla",dur:"03:30",desc:"Afro-Dominican devotional fusion, reveren..."},
  {pos:127,title:"Broken Heart, Steadfast Sound",dur:"03:17",desc:"reverent prophetic Nyabinghi Roots Regga..."},
  {pos:128,title:"Prophet God's Warm Truth",dur:"02:56",desc:"reverent prophetic Nyabinghi Roots Regga..."},
  {pos:129,title:"Three-Drum Truth",dur:"03:46",desc:"reverent prophetic Nyabinghi Roots Regga..."},
  {pos:130,title:"Ceremonial Rise",dur:"03:30",desc:"reverent prophetic Nyabinghi Roots Regga..."},
  {pos:131,title:"Trust in the Hush",dur:"03:15",desc:"uplifting reggae groove with grand piano..."},
  {pos:132,title:"Mercy's Stone",dur:"03:02",desc:"uplifting reggae groove with grand piano..."},
  {pos:133,title:"Trust in the Hush",dur:"02:56",desc:"solemn uplifting Traditional Hymn, melan..."},
  {pos:134,title:"Mercy's Stone",dur:"03:53",desc:"solemn uplifting Traditional Hymn, melan..."},
  {pos:135,title:"Trust in the Stone",dur:"02:50",desc:"spiritual Roots Reggae with Nyabinghi ba..."},
  {pos:136,title:"Heartbeat and Mercy",dur:"03:06",desc:"spiritual Roots Reggae with Nyabinghi ba..."},
  {pos:137,title:"Mercy Stone Steadfast",dur:"03:33",desc:"serene Devotional Nyabinghi Roots Regga..."},
  {pos:138,title:"Hushed Faithful Promise",dur:"05:11",desc:"serene Devotional Nyabinghi Roots Regga..."},
  {pos:139,title:"Trust in Mercy Stone",dur:"04:37",desc:"triumphant Devotional Nyabinghi Roots Reg..."},
  {pos:140,title:"Mercy Flows Steadfast",dur:"04:19",desc:"triumphant Devotional Nyabinghi Roots Reg..."},
  {pos:141,title:"Mercy Stone",dur:"04:23",desc:"contemplative Devotional Nyabinghi Roots..."},
  {pos:142,title:"Prophet God's Call",dur:"03:37",desc:"contemplative devotional Nyabinghi Roots..."},
  {pos:143,title:"Mercy's Steady Voice",dur:"04:09",desc:"serene, devotional Nyabinghi Roots Regga..."},
  {pos:144,title:"Hushed Faithful Promise",dur:"03:28",desc:"serene, devotional Nyabinghi Roots Regga..."},
  {pos:145,title:"Trust in Mercy Alone",dur:"04:17",desc:"triumphant, devotional Nyabinghi Roots Re..."},
  {pos:146,title:"Mercy Flows Steady",dur:"04:04",desc:"triumphant, devotional Nyabinghi Roots Re..."},
  {pos:147,title:"Mercy's Steady Stone",dur:"04:27",desc:"A steady, moderate Nyabinghi Roots Regga..."},
  {pos:148,title:"Prophet God's Call",dur:"04:26",desc:"A steady, moderate Nyabinghi Roots Regga..."},
  {pos:149,title:"Prophet Gad Speaks",dur:"05:09",desc:"reverent prophetic Devotional Nyabinghi R..."},
  {pos:150,title:"Flesh Will Fail",dur:"05:00",desc:"reverent prophetic Devotional Nyabinghi R..."},
  {pos:151,title:"Mercy's Throne",dur:"05:03",desc:"reverent prophetic Devotional Nyabinghi R..."},
  {pos:152,title:"Soft Bass and Skanks",dur:"03:53",desc:"serene devotional Nyabinghi Roots Regga..."},
  {pos:153,title:"Peaceful Shofar Outro",dur:"04:40",desc:"serene devotional Nyabinghi Roots Regga..."},
  {pos:154,title:"God Builds on Mercy Stone",dur:"05:11",desc:"reverent prophetic Devotional Nyabinghi R..."},
  {pos:155,title:"Trust in Mercy Alone",dur:"03:48",desc:"reverent prophetic Devotional Nyabinghi R..."},
  {pos:156,title:"Horns and Mercy Fade",dur:"03:56",desc:"devotional Nyabinghi Roots Reggae, prop..."},
  {pos:157,title:"Dub Extension Rising",dur:"04:38",desc:"devotional Nyabinghi Roots Reggae, prop..."},
  {pos:158,title:"Guitar Hymn of Trust",dur:"04:55",desc:"solemn uplifting Traditional Hymn, melanc..."},
  {pos:159,title:"Trust in God Alone",dur:"04:15",desc:"solemn uplifting Traditional Hymn, melanc..."},
  {pos:160,title:"The Arm of Flesh",dur:"04:27",desc:"solemn uplifting Traditional Hymn, melanc..."},
  {pos:161,title:"Trust in God Alone",dur:"04:03",desc:"solemn uplifting Traditional Hymn, melanc..."},
  {pos:162,title:"Breakdown Rush",dur:"02:00",desc:"euphoric Rave, intense rhythmic drive, asc..."},
  {pos:163,title:"Rising Energy",dur:"02:00",desc:"euphoric Rave, intense rhythmic drive, asc..."},
  {pos:164,title:"Dark Club Pulse",dur:"02:00",desc:"dark gritty Rave, tense ominous mood, thu..."},
  {pos:165,title:"Rumbling Underground Beat",dur:"02:00",desc:"dark gritty Rave, tense ominous mood, thu..."},
  {pos:166,title:"130 BPM Rush",dur:"02:48",desc:"energetic Rave, intense, pulsing analog sy..."},
  {pos:167,title:"Rave Drive",dur:"02:59",desc:"energetic Rave, intense, pulsing analog sy..."},
  {pos:168,title:"Hand in Hand Daily",dur:"05:11",desc:"ecstatic spiritual 70s Roots Reggae with d..."},
  {pos:169,title:"Walk With Enoch",dur:"04:35",desc:"ecstatic spiritual 70s Roots Reggae with d..."},
  {pos:170,title:"Hand in Hand Daily",dur:"04:48",desc:"ecstatic spiritual 70s Roots Reggae, deep..."},
  {pos:171,title:"Walk With Enoch V3",dur:"05:11",desc:"ecstatic spiritual 70s Roots Reggae, deep..."},
  {pos:172,title:"Warning in the Dark V3",dur:"04:06",desc:"Dub Reggae, Steppers Beat, Four on the f..."},
  {pos:173,title:"Warning in the Dark V2",dur:"03:15",desc:"Dub Reggae, Steppers Beat, Four on the f..."},
  {pos:174,title:"Hand in Hand",dur:"04:19",desc:"70s Roots Reggae, Deep Dub Bass, Cinem..."},
  {pos:175,title:"As Enoch Walked",dur:"04:05",desc:"70s Roots Reggae, Deep Dub Bass, Cinem..."},
  {pos:176,title:"Hand in Hand",dur:"04:44",desc:"70s Roots Reggae, Deep Dub Bass, Cinem..."},
  {pos:177,title:"As Enoch Walked",dur:"04:00",desc:"70s Roots Reggae, Deep Dub Bass, Cinem..."},
  {pos:178,title:"Hand in Hand",dur:"04:29",desc:"Deep dub emphasis with heavy dub bass..."},
  {pos:179,title:"As Enoch Walked",dur:"05:11",desc:"Deep dub emphasis with heavy dub bass..."},
  {pos:180,title:"Ancient Scroll Sound",dur:"03:25",desc:"(Dub Reggae, Steppers beat, Four on the fl..."},
  {pos:181,title:"Prophet's Warning",dur:"04:23",desc:"Dub Reggae, Steppers Beat, Four on the fl..."},
  {pos:182,title:"Warning in the Dark",dur:"03:43",desc:"(Dub Reggae, Steppers Beat, Four on the fl..."},
  {pos:183,title:"Perfect Hatred",dur:"04:01",desc:"(Dub Reggae, Steppers Beat, Four on the fl..."},
  {pos:184,title:"Hand in Hand with Grace",dur:"05:11",desc:"Roots Reggae, Gospel Reggae style with v..."},
  {pos:185,title:"As Enoch Walked",dur:"05:02",desc:"Roots Reggae, Gospel Reggae style with v..."},
  {pos:186,title:"Hand in Hand with Grace",dur:"02:36",desc:"Roots Reggae, Gospel Reggae style with v..."},
  {pos:187,title:"As Enoch Walked",dur:"03:14",desc:"Roots Reggae, Gospel Reggae style with v..."},
  {pos:188,title:"Bass of Judgment",dur:"05:11",desc:"aggressive dub reggae pulse with militant..."},
  {pos:189,title:"Perfect Hatred",dur:"03:49",desc:"aggressive dub reggae pulse with militant..."},
  {pos:190,title:"Prophet's Warning",dur:"03:42",desc:"dark, ominous Dub Reggae with driving st..."},
  {pos:191,title:"Dark Echo Chamber",dur:"03:41",desc:"dark, ominous Dub Reggae with driving st..."},
  {pos:192,title:"Prophet's Call",dur:"03:27",desc:"Intense prophetic chant in dub reggae sty..."},
  {pos:193,title:"Perfect Hatred",dur:"05:11",desc:"Intense prophetic chant in dub reggae sty..."},
  {pos:194,title:"Heartbeat and Soul",dur:"03:09",desc:"spiritual Nyabinghi Roots Reggae, thunder..."},
  {pos:195,title:"Full Groove Peace",dur:"04:12",desc:"spiritual Nyabinghi Roots Reggae, thunder..."},
  {pos:196,title:"Peace in the Rhythm",dur:"02:03",desc:"meditative, spiritual Nyabinghi Roots Regg..."},
  {pos:197,title:"Heartbeat Echoes",dur:"02:25",desc:"meditative, spiritual Nyabinghi Roots Regg..."},
  {pos:198,title:"River of Souls",dur:"03:34",desc:"meditative Nyabinghi Roots Reggae..."},
  {pos:199,title:"Heartbeat of Peace",dur:"04:34",desc:"meditative Nyabinghi Roots Reggae..."},
  {pos:200,title:"Hand That Guides",dur:"03:53",desc:"meditative Nyabinghi Roots Reggae, deep..."},
  {pos:201,title:"He Leadeth Me",dur:"03:18",desc:"meditative Nyabinghi Roots Reggae, deep..."},
  {pos:202,title:"Drum and Spirit",dur:"02:45",desc:"devotional Nyabinghi Roots Reggae, thund..."},
  {pos:203,title:"Thunder Road Hymn",dur:"03:12",desc:"devotional Nyabinghi Roots Reggae, thund..."},
  {pos:204,title:"Hand of Guidance",dur:"02:50",desc:"roots reggae, Nyabinghi rhythm, deep ba..."},
  {pos:205,title:"He Leadeth Me Reggae",dur:"03:12",desc:"roots reggae, Nyabinghi rhythm, deep ba..."},
  {pos:206,title:"Garden of Thunder V3",dur:"03:28",desc:"prophetic Male Raspy Vocal, precise hymn..."},
  {pos:207,title:"Soprano in the Dub",dur:"03:20",desc:"Nyabinghi Roots Reggae with thunderous..."},
  {pos:208,title:"Garden Voice Rising",dur:"03:14",desc:"Nyabinghi Roots Reggae with thunderous..."},
  {pos:209,title:"Thunder Road Gospel",dur:"03:39",desc:"devotional Nyabinghi Roots Reggae, thund..."},
  {pos:210,title:"Pilgrim Praise Journey",dur:"01:58",desc:"prophetic Nyabinghi Roots Reggae with ra..."},
  {pos:211,title:"Everlasting Arms Rise",dur:"02:27",desc:"prophetic Nyabinghi Roots Reggae with th..."},
  {pos:212,title:"Roots and Refuge",dur:"03:38",desc:"prophetic Nyabinghi Roots Reggae with th..."},
  {pos:213,title:"Everlasting Arms Reggae",dur:"03:35",desc:"prophetic Nyabinghi Roots Reggae with th..."},
  {pos:214,title:"(cut from src1)",dur:"03:35",desc:"prophetic Nyabinghi Roots Reggae with th..."},
  {pos:215,title:"Leaning on the Everlasting Ar...",dur:"02:15",desc:"Emphasize the raspy male vocal deliverin..."},
  {pos:216,title:"Dawn Voice in the Garden",dur:"05:11",desc:"Prophetic Roots Reggae, urgent and revel..."},
  {pos:217,title:"Garden of the Prophet",dur:"03:52",desc:"Prophetic Roots Reggae, urgent and revel..."},
  {pos:218,title:"Morning Chant",dur:"03:13",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:219,title:"Ancient Light",dur:"03:13",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:220,title:"Drum of Faith",dur:"03:42",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:221,title:"Ancient Pulse",dur:"03:03",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:222,title:"Chant with Silence",dur:"03:15",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:223,title:"Breath of the Ancients",dur:"02:55",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:224,title:"Tribal Light Prayer",dur:"02:52",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:225,title:"Ancient Heartbeat Chant",dur:"03:05",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:226,title:"Heartbeat of Faith",dur:"02:39",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:227,title:"Dawn Prayer Chant",dur:"02:37",desc:"spiritual, minimalist Nyabinghi Roots Reg..."},
  {pos:228,title:"Spirit-Led Path",dur:"05:10",desc:"devotional reggae dub, deep raspy..."},
  {pos:229,title:"Fire Call Again",dur:"05:10",desc:"devotional roots-reggae dub, deep raspy..."},
  {pos:230,title:"Eternal Father Strong to Save",dur:"05:09",desc:"devotional roots-reggae dub, deep raspy..."},
  {pos:231,title:"Prophet's Fire Call",dur:"04:39",desc:"devotional roots Reggae Dub, deep raspy..."},
  {pos:232,title:"Voice in the Wilderness",dur:"04:31",desc:"devotional Roots Reggae Dub with bubblin..."},
  {pos:233,title:"Fire Call, Spirit-Led",dur:"04:50",desc:"devotional Roots Reggae Dub with bubblin..."},
  {pos:234,title:"Eternal Father",dur:"05:10",desc:"devotional roots Reggae Dub with bubblin..."},
  {pos:235,title:"Prophet's Fire Call",dur:"05:10",desc:"devotional Roots Reggae Dub with bubblin..."},
  {pos:236,title:"Spirit-Led Path",dur:"05:09",desc:"82 BPM F minor roots-reggae dub devotio..."},
  {pos:237,title:"Fire Call Rising",dur:"04:30",desc:"82 BPM F minor roots-reggae dub devotio..."},
  {pos:238,title:"Eternal Father",dur:"06:11",desc:"82 BPM F minor roots-reggae dub devotio..."},
  {pos:239,title:"Prophet's Fire Call",dur:"06:07",desc:"82 BPM F minor roots-reggae dub devotio..."},
  {pos:240,title:"Eternal Father Dub",dur:"05:10",desc:"82 BPM in F minor roots-reggae dub devot..."},
  {pos:241,title:"Prophet's Fire Call",dur:"05:10",desc:"82 BPM in F minor roots-reggae dub devot..."},
  {pos:242,title:"Eternal Father Dub",dur:"05:09",desc:"82 BPM in F minor roots-reggae dub devot..."},
  {pos:243,title:"Prophet's Fire Call",dur:"05:09",desc:"82 BPM in F minor roots-reggae dub devot..."},
  {pos:244,title:"Thunder and the Wall",dur:"02:25",desc:"Mystical Roots Reggae, prophetic atmosp..."},
  {pos:245,title:"Rising Ark Chant",dur:"02:07",desc:"Mystical Roots Reggae, prophetic atmosp..."},
  {pos:246,title:"Walking the Prophetic Line",dur:"05:11",desc:"Mystical Roots Reggae emphasizing deep..."},
  {pos:247,title:"Revelation Bass Journey",dur:"05:11",desc:"Mystical Roots Reggae emphasizing deep..."},
  {pos:248,title:"Rising Thunder",dur:"05:11",desc:"Meditative Roots Reggae building from dis..."},
  {pos:249,title:"Exile's Plea",dur:"05:11",desc:"Meditative Roots Reggae building from dis..."},
  {pos:250,title:"Thunder Roll Praise",dur:"05:10",desc:"dub reggae, nyabinghi drums, 80 bpm, m..."},
  {pos:251,title:"Eternal Father Strong to Save",dur:"05:10",desc:"dub reggae, nyabinghi drums, 80 bpm, m..."},
  {pos:252,title:"Thunder Roll Praise",dur:"04:49",desc:"ecstatic, conscious Gospel Dub Reggae wi..."},
  {pos:253,title:"Eternal Father Strong to Save",dur:"05:08",desc:"ecstatic, conscious Gospel Dub Reggae wi..."},
  {pos:254,title:"Heartbeat of Praise",dur:"05:10",desc:"STYLE: Nyabinghi-rooted dub reggae meet..."},
  {pos:255,title:"Thunder and Grace",dur:"05:10",desc:"STYLE: Nyabinghi-rooted dub reggae meet..."},
  {pos:256,title:"Thunder and Grace",dur:"05:10",desc:"STYLE: Nyabinghi-rooted dub reggae meet..."},
  {pos:257,title:"Eternal Father Strong to Save",dur:"05:10",desc:"STYLE: Nyabinghi-rooted dub reggae meet..."},
  {pos:258,title:"Thunder and Grace",dur:"06:04",desc:"STYLE: Nyabinghi-rooted dub reggae meet..."},
  {pos:259,title:"Heartbeat of Praise",dur:"05:23",desc:"STYLE: Nyabinghi-rooted dub reggae meet..."},
  {pos:260,title:"Drum Roll Faith",dur:"05:11",desc:"reflective Roots Reggae with bubbling Ha..."},
  {pos:261,title:"Hammond's Rising Call",dur:"05:11",desc:"reflective Roots Reggae with bubbling Ha..."},
  {pos:262,title:"Thunder and Grace",dur:"04:39",desc:"atmospheric Deep Dub with bubbling Ha..."},
  {pos:263,title:"Deep Echoes of Faith",dur:"04:52",desc:"atmospheric Deep Dub with bubbling Ha..."},
  {pos:264,title:"Hammond's Call",dur:"04:16",desc:"prominent bubbling Hammond B3 organ l..."},
  {pos:265,title:"Bubbling Faith",dur:"03:59",desc:"prominent bubbling Hammond B3 organ l..."},
  {pos:266,title:"Watchman's Hymn",dur:"05:06",desc:"soften the atmosphere with swirling organ..."},
  {pos:267,title:"No Shadow of Turning",dur:"05:06",desc:"soften the atmosphere with swirling organ..."},
  {pos:268,title:"No Shadow Turning",dur:"05:05",desc:"solemn Roots Reggae with nyabinghi ha..."},
  {pos:269,title:"Watchman's Warning",dur:"05:05",desc:"solemn Roots Reggae with nyabinghi ha..."},
  {pos:270,title:"No Shadow Turning",dur:"05:05",desc:"(emphasize funde drums and walking bass..."},
  {pos:271,title:"Watchman's Call",dur:"05:05",desc:"(emphasize funde drums and walking bass..."},
  {pos:272,title:"Watchman's Call",dur:"05:06",desc:"slow nyabinghi roots reggae 66bpm one-..."},
  {pos:273,title:"No Shadow of Turning",dur:"05:06",desc:"slow nyabinghi roots reggae 66bpm one-..."},
  {pos:274,title:"Watchman on Zion's Wall",dur:"05:05",desc:"dub roots reggae, nyabinghi drums, one..."},
  {pos:275,title:"No Shadow of Turning",dur:"05:05",desc:"dub roots reggae, nyabinghi drums, one..."},
  {pos:276,title:"No Shadow of Turning V4",dur:"05:03",desc:"roots reggae, nyabinghi, one-drop, 66 BP..."},
  {pos:277,title:"No Shadow of Turning V3",dur:"05:08",desc:"roots reggae, nyabinghi, one-drop, 66 BP..."},
  {pos:278,title:"Watchman on Zion's Gate",dur:"05:08",desc:"solemn Nyabinghi Roots Reggae, meditati..."},
  {pos:279,title:"No Shadow of Turning",dur:"05:08",desc:"solemn Nyabinghi Roots Reggae, meditati..."},
  {pos:280,title:"No Shadow of Turning",dur:"04:54",desc:"solemn Roots Reggae, meditative dread, d..."},
  {pos:281,title:"Prophet's Warning",dur:"05:11",desc:"solemn Roots Reggae, meditative dread, d..."},
  {pos:282,title:"No Shadow of Turning",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditative dread, d..."},
  {pos:283,title:"Prophet's Call",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditative dread, d..."},
  {pos:284,title:"No Shadow of Turning",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditative dread, d..."},
  {pos:285,title:"Eternal Father's Warning",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:286,title:"No Shadow of Turning",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:287,title:"Prophetic Chant Rising",dur:"04:40",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:288,title:"No Shadow of Turning",dur:"04:37",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:289,title:"Deep Nyabinghi Chant",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:290,title:"No Shadow of Turning",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:291,title:"Three Messengers Cry",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:292,title:"Unchanging God",dur:"04:24",desc:"solemn Nyabinghi Roots Reggae, meditati..."},
  {pos:293,title:"Three Messengers",dur:"03:43",desc:"solemn Nyabinghi Roots Reggae, meditati..."},
  {pos:294,title:"Unchanging God",dur:"04:13",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:295,title:"Three Messengers",dur:"04:08",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:296,title:"Unchanging God",dur:"04:35",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:297,title:"Eternal Father's Call",dur:"04:37",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:298,title:"Thunder and the Scroll",dur:"05:11",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:299,title:"No Shadow of Turning",dur:"05:08",desc:"solemn Nyabinghi Roots Reggae, meditativ..."},
  {pos:300,title:"Rising Lines from the Wall",dur:"03:06",desc:"reverent Roots Reggae, Nyabinghi dub, mo..."},
  {pos:301,title:"Horn Call to the Father",dur:"03:47",desc:"reverent Roots Reggae, Nyabinghi dub, mo..."},
  {pos:302,title:"Voice on High",dur:"05:10",desc:"meditative Roots Reggae, Nyabinghi dub, s..."},
  {pos:303,title:"Call to Mercy",dur:"05:08",desc:"reverent Roots Reggae with deep pulsating..."},
  {pos:304,title:"Written on the Wall",dur:"05:08",desc:"reverent Roots Reggae with deep pulsating..."},
  {pos:305,title:"Written on the Wall",dur:"05:07",desc:"Meditative Nyabinghi Dub with sparse Nyab..."},
  {pos:306,title:"Eternal Father Calling",dur:"05:07",desc:"Meditative Nyabinghi Dub with sparse Nyab..."},
  {pos:307,title:"Rise to the Warning",dur:"05:09",desc:"triumphant Roots Reggae, ecstatic Hammo..."},
  {pos:308,title:"The Hand is Writing Still",dur:"04:28",desc:"triumphant Roots Reggae, ecstatic Hammo..."},
  {pos:309,title:"Voices on the Wall",dur:"05:10",desc:"prophetic Roots Reggae, urgent and revere..."},
  {pos:310,title:"The Hand is Writing",dur:"05:10",desc:"prophetic Roots Reggae, urgent and revere..."},
  {pos:311,title:"Writing on the Wall",dur:"05:09",desc:"roots reggae spiritual song emphasizing q..."},
  {pos:312,title:"Rise and Read the Sign",dur:"04:21",desc:"prophetic, mystical Roots Reggae with hyp..."},
  {pos:313,title:"Burning Words on the Wall",dur:"04:11",desc:"prophetic, mystical Roots Reggae with hyp..."},
  {pos:314,title:"Rise and Read the Sign",dur:"04:02",desc:"contemplative, prophetic Roots Reggae wit..."},
  {pos:315,title:"Burning Words on the Wall",dur:"04:22",desc:"contemplative, prophetic Roots Reggae wit..."},
  {pos:316,title:"Hand of Fire",dur:"03:12",desc:"ritualistic Roots Reggae, hypnotic polyrhyth..."},
  {pos:317,title:"Writing On The Wall",dur:"03:59",desc:"ritualistic Roots Reggae, hypnotic polyrhyth..."},
  {pos:318,title:"Bass and Prophecy",dur:"02:46",desc:"mystical Roots Reggae, prophetic atmosph..."},
  {pos:319,title:"Drum Waves Rise",dur:"02:54",desc:"mystical Roots Reggae, prophetic atmosph..."},
  {pos:320,title:"Nyabinghi Echoes",dur:"02:44",desc:"mystical Roots Reggae, prophetic atmosph..."},
  {pos:321,title:"Bass Prophecy Rising",dur:"02:32",desc:"mystical Roots Reggae, prophetic atmosph..."},
  {pos:322,title:"Ritual Bass Flow",dur:"03:25",desc:"mystical Roots Reggae, prophetic atmosph..."},
  {pos:323,title:"Writing on the Wall",dur:"03:25",desc:"mystical Roots Reggae, prophetic atmosph..."},
  {pos:324,title:"Voice from the Sky",dur:"05:09",desc:"spiritual Chant Groove with rolling one-dro..."},
  {pos:325,title:"The Writing on the Wall",dur:"04:46",desc:"spiritual Chant Groove with rolling one-dro..."},
  {pos:326,title:"Voice from the Sky",dur:"05:11",desc:"prophetic Cinematic Dub with heavy sub b..."},
  {pos:327,title:"The Writing on the Wall",dur:"05:11",desc:"prophetic Cinematic Dub with heavy sub b..."},
  {pos:328,title:"Voice from the Sky",dur:"04:59",desc:"meditative, prophetic Dub with heavy sub b..."},
  {pos:329,title:"The Writing on the Wall",dur:"04:55",desc:"meditative, prophetic Dub with heavy sub b..."},
  {pos:330,title:"Prophet's Warning",dur:"04:10",desc:"dominican bachata, requinto guitar, bon..."},
  {pos:331,title:"Writing on the Wall",dur:"04:09",desc:"dominican bachata, requinto guitar, bon..."},
  {pos:332,title:"Rusty Nail Prophecy",dur:"05:11",desc:"bachata, raw authentic hardcore style, fr..."},
  {pos:333,title:"Writing on the Wall",dur:"04:08",desc:"bachata, raw authentic hardcore style, fr..."},
  {pos:334,title:"Nail on the Wall",dur:"05:30",desc:"Authentic Haitian Kompa, electric guitar..."},
  {pos:335,title:"Writing on the Wall",dur:"04:37",desc:"Authentic Haitian Kompa, electric guitar..."},
  {pos:336,title:"Rusty Nail Prophecy",dur:"04:59",desc:"dominican bachata, raw sensual requin..."},
  {pos:337,title:"Writing on the Wall",dur:"04:42",desc:"dominican bachata, raw sensual requin..."},
  {pos:338,title:"Llamada del Juicio Final",dur:"04:21",desc:"dominican bachata, raw sensual requin..."},
  {pos:339,title:"La Escritura en la Pared",dur:"04:08",desc:"dominican bachata, raw sensual requin..."},
  {pos:340,title:"Llamada del Juicio Final",dur:"04:53",desc:"dominican bachata, heartfelt sensual p..."},
  {pos:341,title:"La Escritura en la Pared",dur:"04:32",desc:"dominican bachata, heartfelt sensual p..."},
  {pos:342,title:"Voices on the Mirror",dur:"03:06",desc:"haitian roots reggae, rara fusion, vodou..."},
  {pos:343,title:"Ekriti Sou Miray La",dur:"04:06",desc:"haitian roots reggae, rara fusion, vodou..."},
  {pos:344,title:"One Nail Tells All",dur:"02:09",desc:"Deep Roots Reggae, bubbling Hammon..."},
  {pos:345,title:"The Wall Still Stands",dur:"03:11",desc:"Deep Roots Reggae, bubbling Hammon..."},
  {pos:346,title:"The Wall Still Stands",dur:"04:54",desc:"Deep Roots Reggae, Nyabinghi hand dr..."},
  {pos:347,title:"One Nail Tells All",dur:"05:01",desc:"Deep Roots Reggae, Nyabinghi hand dr..."},
  {pos:348,title:"One Nail Tells All",dur:"02:06",desc:"Deep Roots Reggae, Nyabinghi hand dr..."},
  {pos:349,title:"The Wall Still Stands",dur:"03:31",desc:"Deep Roots Reggae, Nyabinghi hand dr..."},
  {pos:350,title:"Hymn of the Wall V10",dur:"05:49",desc:"deep roots reggae, minor key, solemn p..."},
  {pos:351,title:"Hymn of the Wall V9",dur:"05:41",desc:"deep roots reggae, minor key, solemn p..."},
  {pos:352,title:"Hymn of the Wall V8",dur:"05:52",desc:"deep roots reggae, minor key, solemn p..."},
  {pos:353,title:"Hymn of the Wall V7",dur:"06:44",desc:"deep roots reggae, minor key, solemn p..."},
  {pos:354,title:"Nail on the Wall",dur:"05:19",desc:"Deep Roots Reggae, Nyabinghi hand dr..."},
  {pos:355,title:"The Writing Calls",dur:"05:41",desc:"Deep Roots Reggae, Nyabinghi hand dr..."},
  {pos:356,title:"Hymn of Judgment",dur:"04:32",desc:"Solemn Hymn, pipe organ, choral harm..."},
  {pos:357,title:"The Nail Speaks",dur:"04:17",desc:"Solemn Hymn, pipe organ, choral harm..."},
  {pos:358,title:"Hear the Writing",dur:"03:44",desc:"Solemn Hymn, pipe organ, choral harm..."},
  {pos:359,title:"The Nail on the Wall",dur:"04:08",desc:"Solemn Hymn, pipe organ, choral harm..."},
  {pos:360,title:"Hymn of the Wall V6",dur:"05:19",desc:"deep roots reggae, minor key, solemn p..."},
  {pos:361,title:"Hymn of the Wall V5",dur:"04:52",desc:"deep roots reggae, minor key, solemn..."},
  {pos:362,title:"Hymn of the Wall V4",dur:"03:29",desc:"roots reggae, minor key, spiritual dread,..."},
  {pos:363,title:"Hymn of the Wall V3",dur:"03:34",desc:"roots reggae, minor key, spiritual dread,..."},
  {pos:364,title:"Hymn of the Wall",dur:"03:42",desc:"Victorian Hymn, pipe organ, SATB choir..."},
  {pos:365,title:"The Nail's Tale",dur:"03:47",desc:"Victorian Hymn, pipe organ, SATB choir..."},
  {pos:366,title:"One Drop Prophecy V3",dur:"03:52",desc:"Roots Reggae, mystical atmosphere, dee..."},
  {pos:367,title:"The Writing Remains V3",dur:"02:49",desc:"Roots Reggae, mystical atmosphere, dee..."},
  {pos:368,title:"One Drop Prophecy",dur:"02:24",desc:"Roots Reggae, mystical atmosphere, dee..."},
  {pos:369,title:"The Writing Remains",dur:"02:49",desc:"Roots Reggae, mystical atmosphere, dee..."},
  {pos:370,title:"Prophet's Dub Flame V4",dur:"05:36",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:371,title:"Prophet's Dub Flame V3",dur:"05:24",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:372,title:"Prophet's Fire Call V8",dur:"05:23",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:373,title:"Prophet's Fire Call V7",dur:"04:50",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:374,title:"Prophet's Fire Call V6",dur:"05:09",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:375,title:"Dust and Holy Light",dur:"05:47",desc:"Roots Reggae Dub, devotional, ecstatic j..."},
  {pos:376,title:"Seven Calls to Fire",dur:"06:08",desc:"Roots Reggae Dub, devotional, ecstatic j..."},
  {pos:377,title:"Prophet's Fire Call V4",dur:"04:37",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:378,title:"Prophet's Fire Call V3",dur:"04:54",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:379,title:"Prophet's Soil",dur:"03:11",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:380,title:"Fire Call Dub",dur:"03:12",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:381,title:"Prophet's Fire Call",dur:"05:08",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:382,title:"Eternal Father Dub",dur:"05:31",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:383,title:"Prophet's Dub Flame",dur:"05:13",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:384,title:"Eternal Father Call",dur:"05:13",desc:"Roots Reggae Dub, devotional, male dee..."},
  {pos:385,title:"Eternal Father Hear V9",dur:"05:58",desc:"instrumental gospel dub with ecstatic hor..."},
  {pos:386,title:"Eternal Father Hear V8",dur:"06:13",desc:"instrumental gospel dub with ecstatic hor..."},
  {pos:387,title:"Eternal Father Hear V7",dur:"05:14",desc:"roots reggae dub, F minor, 82 BPM, deep..."},
  {pos:388,title:"Eternal Father Hear V6",dur:"05:14",desc:"roots reggae dub, F minor, 82 BPM, deep..."},
  {pos:389,title:"Eternal Father Hear V5",dur:"06:36",desc:"instrumental gospel dub with ecstatic hor..."},
  {pos:390,title:"Eternal Father Hear V4",dur:"06:21",desc:"instrumental gospel dub with ecstatic hor..."},
  {pos:391,title:"Eternal Father Dub",dur:"07:59",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:392,title:"Dub of Devotion",dur:"06:01",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:393,title:"Calling the Father",dur:"06:23",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:394,title:"Dub of Clarity",dur:"06:44",desc:"Roots Reggae Dub, triumphant horns, nya..."},
  {pos:395,title:"Calling the Father",dur:"07:59",desc:"Roots Reggae Dub, triumphant horns, nya..."},
  {pos:396,title:"Calling in the Dub",dur:"03:06",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:397,title:"Eternal Father Dub",dur:"04:31",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:398,title:"Dub of Devotion",dur:"05:55",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:399,title:"Eternal Father Calls",dur:"05:48",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:400,title:"Dub of Clarity",dur:"06:04",desc:"Roots Reggae Dub, triumphant horns, nya..."},
  {pos:401,title:"Eternal Father Call",dur:"06:04",desc:"Roots Reggae Dub, triumphant horns, nya..."},
  {pos:402,title:"Dub Praise Rising",dur:"06:25",desc:"Roots Reggae Dub, triumphant horns, nya..."},
  {pos:403,title:"Eternal Father Call",dur:"04:49",desc:"Roots Reggae Dub, triumphant horns, nya..."},
  {pos:404,title:"Eternal Father Call",dur:"06:24",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:405,title:"Calling in the Dub",dur:"05:56",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:406,title:"Eternal Father Dub",dur:"05:23",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:407,title:"Calling in the Dub V4",dur:"07:29",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:408,title:"Calling in the Dub V3",dur:"05:19",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:409,title:"Calling in the Dub",dur:"05:21",desc:"Roots Reggae Dub, ecstatic full-band pra..."},
  {pos:410,title:"Eternal Father Dub",dur:"05:28",desc:"Roots Reggae Dub, ecstatic full-band pr..."},
  {pos:411,title:"Calling in the Dub V3",dur:"02:18",desc:"Roots Reggae Dub, ecstatic full-band pr..."},
  {pos:412,title:"Eternal Father Dub V3",dur:"02:39",desc:"Roots Reggae Dub, ecstatic full-band pr..."},
  {pos:413,title:"Eternal Father Hear V3",dur:"03:21",desc:"roots reggae dub, F minor, 74 BPM, nyabi..."},
  {pos:414,title:"The Prophet Gad V3",dur:"04:04",desc:"roots reggae dub, F minor, 74 BPM, nyabi..."},
  {pos:415,title:"Calling in the Dub",dur:"04:59",desc:"Roots Reggae Dub, deep sub-bass, bub..."},
  {pos:416,title:"Bass and Prayer",dur:"05:30",desc:"Roots Reggae Dub, deep sub-bass swin..."},
  {pos:417,title:"Deep Calling Dub",dur:"05:28",desc:"Roots Reggae Dub, deep sub-bass swin..."},
  {pos:418,title:"Calling in the Dub",dur:"06:00",desc:"Hybrid Dub, deep sub-bass, bubbling Ha..."},
  {pos:419,title:"Faithful Steps",dur:"04:58",desc:"Hybrid Dub, deep sub-bass, bubbling Ha..."},
  {pos:420,title:"Eternal Father Dub",dur:"05:52",desc:"Very slow, heavy 1970s roots-reggae du..."},
  {pos:421,title:"The Prophet Gad",dur:"05:42",desc:"Very slow, heavy 1970s roots-reggae du..."},
  {pos:422,title:"Roots of Faith",dur:"05:34",desc:"Slow, spiritual roots reggae dub devotion..."},
  {pos:423,title:"The Prophet's Call",dur:"05:42",desc:"Slow, spiritual roots reggae dub devotion..."},
  {pos:424,title:"The Prophet Gad",dur:"06:50",desc:"Dominican Bachata, meditative acoustic..."},
  {pos:425,title:"Whisper from the Dust",dur:"05:13",desc:"Dominican Bachata, meditative acoustic..."},
  {pos:426,title:"The Prophet Gad",dur:"05:33",desc:"Dominican Bachata, meditative acoustic..."},
  {pos:427,title:"Whisper from the Dust",dur:"05:21",desc:"Dominican Bachata, meditative acoustic..."},
  {pos:428,title:"The Prophet Gad",dur:"05:37",desc:"Dominican Bachata, meditative acoustic..."},
  {pos:429,title:"Voz en el Silencio",dur:"05:19",desc:"devotional, dominican spanish..."},
  {pos:430,title:"El Profeta Gad",dur:"05:33",desc:"devotional bachata, dominican spanish..."},
  {pos:431,title:"Voz en el Silencio",dur:"05:01",desc:"devotional bachata, male vocals, prayerf..."},
  {pos:432,title:"El Profeta Gad",dur:"05:09",desc:"devotional bachata, male vocals, prayerf..."},
  {pos:433,title:"Voz en el Silencio",dur:"04:21",desc:"acoustic bachata, F minor, 74 bpm, nylon..."},
  {pos:434,title:"El Profeta Gad",dur:"04:25",desc:"acoustic bachata, F minor, 74 bpm, nylon..."},
  {pos:435,title:"Under Your Sky",dur:"06:21",desc:"Devotional Kompa, minor-key accordion,..."},
  {pos:436,title:"Papa Etènèl",dur:"06:11",desc:"Devotional Kompa, minor-key accordion,..."},
  {pos:437,title:"Path Under Your Sky",dur:"06:18",desc:"Devotional Kompa, heartbeat tanbou rhyt..."},
  {pos:438,title:"Heartbeat of Faith",dur:"05:21",desc:"Devotional Kompa, heartbeat tanbou rhyt..."},
  {pos:439,title:"Wout Mwen",dur:"05:00",desc:"minor-key accordion, slow tempo, hushe..."},
  {pos:440,title:"Papa Etènèl",dur:"04:51",desc:"minor-key accordion, slow tempo, hushe..."},
  {pos:441,title:"Father Hear My Plea",dur:"05:05",desc:"Spiritual Roots Reggae Dub, meditative pi..."},
  {pos:442,title:"The Prophet Gad",dur:"05:24",desc:"Spiritual Roots Reggae Dub, meditative pi..."},
  {pos:443,title:"Soil and Spirit",dur:"04:42",desc:"Spiritual Roots Reggae Dub, nyabinghi ps..."},
  {pos:444,title:"Roots of Grace",dur:"04:43",desc:"Spiritual Roots Reggae Dub, nyabinghi ps..."},
  {pos:445,title:"Eternal Father",dur:"04:54",desc:"Spiritual Roots Reggae Dub, nyabinghi ps..."},
  {pos:446,title:"Fertile Soil",dur:"05:09",desc:"Spiritual Roots Reggae Dub, nyabinghi ps..."},
  {pos:447,title:"Fertile Soil",dur:"05:59",desc:"Spiritual Roots Reggae Dub, pipe organ m..."},
  {pos:448,title:"The Prophet's Call",dur:"05:38",desc:"Spiritual Roots Reggae Dub, pipe organ m..."},
  {pos:449,title:"Guide Me Through",dur:"04:58",desc:"slow pipe-organ meditation in a minor ke..."},
  {pos:450,title:"The Prophet's Return",dur:"04:58",desc:"slow pipe-organ meditation in a minor ke..."},
  {pos:451,title:"Guide Me Home",dur:"05:12",desc:"slow, spiritual Bachata arrangement, nylo..."},
  {pos:452,title:"The Prophet's Call",dur:"05:24",desc:"slow, spiritual Bachata arrangement, nylo..."},
  {pos:453,title:"Guide Me Home",dur:"04:59",desc:"slow, spiritual Bachata arrangement, nylo..."},
  {pos:454,title:"The Prophet Gad",dur:"04:59",desc:"slow, spiritual Bachata arrangement, nylo..."},
  {pos:455,title:"Roots of Grace",dur:"04:24",desc:"Roots Dub Reggae, one-drop percussion,..."},
  {pos:456,title:"The Prophet's Call",dur:"04:06",desc:"Roots Dub Reggae, one-drop percussion,..."},
  {pos:457,title:"Leve Anko",dur:"04:31",desc:"modern Haitian Kompa / Compas Direct..."},
  {pos:458,title:"Ayiti Leve",dur:"04:24",desc:"modern Haitian Kompa / Compas Direct..."},
  {pos:459,title:"Nou Tounen",dur:"03:36",desc:"Modern Kompa, Haitian Creole female vo..."},
  {pos:460,title:"Leve Ayiti",dur:"04:24",desc:"Modern Kompa, Haitian Creole female vo..."},
  {pos:461,title:"Kompa Pou Limyè",dur:"03:44",desc:"Modern Kompa, bachata nylon guitar, sy..."},
  {pos:462,title:"Leve Ayiti",dur:"04:22",desc:"Modern Kompa, bachata nylon guitar, sy..."},
  {pos:463,title:"Kompa Pou Limyè",dur:"03:54",desc:"Modern Kompa, haitian creole vocals, ba..."},
  {pos:464,title:"Leve Ayiti",dur:"04:45",desc:"modern Kompa, haitian creole vocals, ba..."},
  {pos:465,title:"Ayiti Leve Anko",dur:"03:17",desc:"Kompa and carnival stadium anthem wit..."},
  {pos:466,title:"Ayiti Leve Anko",dur:"03:35",desc:"haitian konpa, carnival stadium, tanbou f..."},
  {pos:467,title:"Nuestros Colores Arriba",dur:"03:28",desc:"bachata, nylon guitar, güira, bongo, deep..."},
  {pos:468,title:"Desde el '74, Volvemos",dur:"03:25",desc:"bachata, nylon guitar, güira, bongo, deep..."},
  {pos:469,title:"Haiti Rise Again",dur:"03:49",desc:"Style: Hardcore Dominican Bachata in En..."},
  {pos:470,title:"Since '74, We Return",dur:"04:34",desc:"Style: Hardcore Dominican Bachata in En..."},
  {pos:471,title:"Haiti Rise Again V4",dur:"05:06",desc:"Hardcore Dominican Bachata, driving gri..."},
  {pos:472,title:"Haiti Rise Again V3",dur:"05:55",desc:"Hardcore Dominican Bachata, driving gri..."},
  {pos:473,title:"Depi Swasanndiset",dur:"04:12",desc:"kompa, spiritual patriotic, full band, 94-10..."},
  {pos:474,title:"Ayiti Leve",dur:"04:29",desc:"kompa, spiritual patriotic, full band, 94-10..."},
  {pos:475,title:"Since '74 We Return",dur:"04:47",desc:"Hardcore Dominican Bachata, driving clu..."},
  {pos:476,title:"Haiti Rise Again",dur:"03:56",desc:"Hardcore Dominican Bachata, driving clu..."},
  {pos:477,title:"Since '74 We Return",dur:"05:45",desc:"Hardcore Dominican Bachata, driving gri..."},
  {pos:478,title:"Haiti Rise Again",dur:"05:14",desc:"Hardcore Dominican Bachata, driving gri..."},
  {pos:479,title:"Since '74 We Return",dur:"04:21",desc:"Hardcore Dominican Bachata, driving gri..."},
  {pos:480,title:"Haiti Rise Again",dur:"04:12",desc:"Hardcore Dominican Bachata, driving gri..."},
  {pos:481,title:"Bandera que Canta",dur:"03:29",desc:"bachata, nylon guitar, bongos, güira, 95 B..."},
  {pos:482,title:"Levántate Ya",dur:"03:39",desc:"bachata, nylon guitar, bongos, güira, 95 B..."},
  {pos:483,title:"Baila Fuerte Hoy",dur:"03:22",desc:"bachata Dominicana, nylon guitar, bongo..."},
  {pos:484,title:"Haiti Levántate",dur:"03:07",desc:"Bachata Dominicana, nylon guitar, bongo..."},
  {pos:485,title:"Light the Torch",dur:"03:59",desc:"Pop-Kompa crossover anthem, emotional..."},
  {pos:486,title:"Haiti Rise Again",dur:"03:34",desc:"Pop-Kompa crossover anthem, emotional..."},
  {pos:487,title:"Flambo Limen",dur:"04:19",desc:"Haitian Kompa, spiritual patriotic tone, full..."},
  {pos:488,title:"Ayiti Leve",dur:"04:39",desc:"Haitian Kompa, spiritual patriotic tone, full..."},
  {pos:489,title:"Island Pulse",dur:"04:38",desc:"hardcore bachata, sharp requinto riffs, ag..."},
  {pos:490,title:"Heart of Quisqueya",dur:"05:34",desc:"hardcore bachata, bolero fusion, sharp re..."},
  {pos:491,title:"Island of Bright Courage",dur:"05:14",desc:"hardcore bachata, bolero fusion, sharp re..."},
  {pos:492,title:"Heart of Quisqueya",dur:"05:29",desc:"hardcore bachata, sharp requinto riffs, es..."},
  {pos:493,title:"Island of Bright Courage",dur:"05:18",desc:"hardcore bachata, sharp requinto riffs, es..."},
  {pos:494,title:"Quiet Shore V3",dur:"04:57",desc:"hardcore Dominican bachata, reflective ri..."},
  {pos:495,title:"Quiet Shore",dur:"05:14",desc:"{ AI: Dominican bachata, Sub: hard..."},
  {pos:496,title:"Alina's Warmth",dur:"04:59",desc:"{ AI: Dominican bachata, Sub: hard..."},
  {pos:497,title:"Heatwave Groove V4",dur:"03:41",desc:"bachata reggaeton fusion, sharp high-p..."},
  {pos:498,title:"Heatwave Groove V3",dur:"03:59",desc:"bachata reggaeton fusion, sharp high-p..."},
  {pos:499,title:"Hardcore Alina",dur:"03:54",desc:"Dominican Bachata Intenso, riffs agresiv..."},
  {pos:500,title:"Alina",dur:"04:42",desc:"Dominican Bachata Intenso, riffs agresiv..."},
  {pos:501,title:"Caribbean Fire",dur:"03:19",desc:"intenso bachata dominicano hardcore, t..."},
  {pos:502,title:"Alina",dur:"03:49",desc:"intenso bachata dominicano hardcore, t..."},
  {pos:503,title:"Hardcore Caribbean Night",dur:"03:31",desc:"Bachata dominicana hardcore, riffs agre..."},
  {pos:504,title:"Alina, Dous Alina",dur:"03:54",desc:"Bachata dominicana hardcore, riffs agre..."},
  {pos:505,title:"Hardcore Bachata Night",dur:"04:09",desc:"Dominican Bachata hardcore, riffs agres..."},
  {pos:506,title:"Alina, Dous Alina",dur:"03:54",desc:"Dominican Bachata hardcore, riffs agres..."},
  {pos:507,title:"Summer Heat and Memory",dur:"03:40",desc:"Hardcore-доминиканская бачата, агр..."},
  {pos:508,title:"Alina",dur:"04:07",desc:"Hardcore-доминиканская бачата, агре..."},
  {pos:509,title:"Hardcore Bachata Alina",dur:"03:44",desc:"Hardcore доминиканская бачата, агре..."},
  {pos:510,title:"Alina",dur:"03:24",desc:"Hardcore доминиканская бачата, агре..."},
  {pos:511,title:"República de Mi Corazón",dur:"04:34",desc:"Hardcore бачата в доминиканском стил..."},
  {pos:512,title:"Isla Que Me Acogió",dur:"04:02",desc:"Hardcore бачата в доминиканском стил..."},
  {pos:513,title:"Destino y Fuego",dur:"05:03",desc:"Duro Bachata Dominicano, riffs agresivos..."},
  {pos:514,title:"Amare",dur:"05:07",desc:"Duro Bachata Dominicano, riffs agresivos..."},
  {pos:515,title:"Fuego en la Noche",dur:"03:31",desc:"Hardcore доминиканская бачата, агре..."},
  {pos:516,title:"Fiera Selena",dur:"03:40",desc:"Hardcore доминиканская бачата, агре..."},
  {pos:517,title:"Corazón Firme",dur:"03:29",desc:"Hardcore доминиканская бачата, агре..."},
  {pos:518,title:"Serena",dur:"03:39",desc:"Hardcore доминиканская бачата, агре..."},
  {pos:519,title:"Corazón Abierto",dur:"03:41",desc:"Bachata dominicana hardcore, con riffs..."},
  {pos:520,title:"Alina, Dulce Alina",dur:"03:59",desc:"Bachata dominicana hardcore, con riffs..."},
  {pos:521,title:"Destined Love V3",dur:"04:53",desc:"hardcore Bachata dominicano, aggressi..."},
  {pos:522,title:"Amare V3",dur:"05:14",desc:"hardcore bachata dominicano, aggressi..."},
  {pos:523,title:"One Week with You V3",dur:"04:47",desc:"bachata hardcore, sharp requinto riffs, e..."},
  {pos:524,title:"Alina, My Peace V3",dur:"05:14",desc:"bachata hardcore, sharp requinto riffs, e..."},
  {pos:525,title:"Shelter of the Sea",dur:"05:21",desc:"Duro fusión de bachata dominicana y b..."},
  {pos:526,title:"Island of My Heart",dur:"05:26",desc:"Hardcore bachata dominicana y b..."},
  {pos:527,title:"Destined Love",dur:"05:41",desc:"Hardcore Bachata dominicana, riffs agre..."},
  {pos:528,title:"Amare",dur:"04:99",desc:"Hardcore Bachata dominicana, riffs agre..."},
  {pos:529,title:"Fire in the Year",dur:"03:44",desc:"Duro Bachata Hardcore, con riffs agresiv..."},
  {pos:530,title:"Fierce Selena",dur:"04:28",desc:"Duro Bachata Hardcore, con riffs agresiv..."},
  {pos:531,title:"Steady Like a Song",dur:"04:07",desc:"Hardcore Bachata dominicana, riffs agu..."},
  {pos:532,title:"Serena",dur:"04:27",desc:"Hardcore Bachata dominicana, riffs agu..."},
  {pos:533,title:"Alina, My Peace",dur:"05:12",desc:"Bachata Hardcore, riffs agudos de requi..."},
  {pos:534,title:"Papye Sa M Pa Sot Enviye",dur:"03:25",desc:"Kompa, Haitian Creole Lyrics, Haitian Cre..."},
  {pos:535,title:"Moitié Mwen nan Lonbraj Ou",dur:"03:00",desc:"Kompa, Haitian Creole Lyrics, Haitian Cre..."},
  {pos:536,title:"Carta Sin Enviar",dur:"03:36",desc:"Bachata, syncopated rhythm, bright req..."},
  {pos:537,title:"Mitad de Mi Alma",dur:"03:02",desc:"Bachata, syncopated rhythm, bright req..."},
  {pos:538,title:"Never Held You Close Enoug...",dur:"03:21",desc:"Bachata, romantic mood, smooth male v..."},
  {pos:539,title:"Half My Heart in Your Shado...",dur:"03:16",desc:"Bachata, romantic mood, smooth male v..."},
  {pos:540,title:"Bachata Pulse",dur:"02:36",desc:"bachata reggaeton fusion, sharp high-pi..."},
  {pos:541,title:"Heatwave Groove",dur:"02:16",desc:"bachata reggaeton fusion, sharp high-pi..."},
  {pos:542,title:"Syncopated Streets",dur:"02:26",desc:"bachata reggaeton fusion, steel-string g..."},
  {pos:543,title:"Steel String Sunrise",dur:"03:22",desc:"bachata reggaeton fusion, steel-string g..."},
  {pos:544,title:"Bachata Beat Blend",dur:"02:46",desc:"bachata reggaeton fusion, nylon-string..."},
  {pos:545,title:"Sunny Guitar Flow",dur:"02:17",desc:"bachata reggaeton fusion, nylon-string..."},
  {pos:546,title:"Sharp Bachata Pulse",dur:"02:54",desc:"dominican bachata, sharp high-pitch gu..."},
  {pos:547,title:"Fiery Guitar Drive",dur:"02:59",desc:"dominican bachata, sharp high-pitch gu..."},
  {pos:548,title:"Clean Bachata Pulse",dur:"02:48",desc:"Dominican bachata, bright steel-string g..."},
  {pos:549,title:"Bright Strings Groove",dur:"02:07",desc:"Dominican bachata, bright steel-string g..."},
  {pos:550,title:"Heritage Bachata Groove",dur:"02:41",desc:"dominican bachata, nylon-string guitar,..."},
  {pos:551,title:"Romantic Nylon Rhythm",dur:"03:18",desc:"dominican bachata, nylon-string guitar,..."},
  {pos:552,title:"Dancefloor Heat",dur:"02:48",desc:"dominican bachata, nylon-string guitar,..."},
  {pos:553,title:"Burning Down Tonight",dur:"02:34",desc:"dominican bachata, nylon-string guitar,..."},
  {pos:554,title:"Replay Until It Breaks",dur:"03:19",desc:"Modern Pop Bachata, clean electric guit..."},
  {pos:555,title:"Silence After Your Voice",dur:"02:37",desc:"Modern Pop Bachata, clean electric guit..."},
  {pos:556,title:"Morning Light Without You",dur:"02:44",desc:"Classic Dominican Bachata, nylon-string..."},
  {pos:557,title:"Your Scarf and the Rain",dur:"02:44",desc:"Classic Dominican Bachata, nylon-string..."},
  {pos:558,title:"Hazy Nylon Drift",dur:"02:24",desc:"lo-fi Bachata, heavily saturated nylon g..."},
  {pos:559,title:"Tape-Worn Bachata Groove",dur:"02:47",desc:"lo-fi Bachata, heavily saturated nylon g..."},
  {pos:560,title:"Airy Keys & Guira",dur:"02:36",desc:"Lo-Fi Bachata, airy electric piano chords,..."},
  {pos:561,title:"Bachata in the Backroom",dur:"01:56",desc:"Lo-Fi Bachata, nylon-string guitar arpeg..."},
  {pos:562,title:"Warm Guitar Lo-Fi",dur:"02:24",desc:"Lo-Fi Bachata, nylon-string guitar arpeg..."},
  {pos:563,title:"Neighborhood Burn V3",dur:"03:49",desc:"urban bachata, nylon guitar, deep synth..."},
  {pos:564,title:"Back in the Rain V3",dur:"03:14",desc:"urban bachata, nylon guitar, deep synth..."},
  {pos:565,title:"Shattering the Throne",dur:"04:34",desc:"orchestral bachata, sweeping strings, ..."},
  {pos:566,title:"Thunder in Your Veins",dur:"04:28",desc:"orchestral bachata, sweeping strings, he..."},
  {pos:567,title:"Neighborhood Burn",dur:"03:54",desc:"urban bachata, nylon-string guitar, dee..."},
  {pos:568,title:"Streetlight Reunion",dur:"03:49",desc:"urban bachata, nylon guitar, sync..."},
  {pos:569,title:"Back in the Rain",dur:"03:59",desc:"urban bachata, nylon guitar, sync..."},
  {pos:570,title:"Bachata Morning V4",dur:"02:11",desc:"Acoustic Bachata, fingerstyle guitar, soft..."},
  {pos:571,title:"November Breeze V5",dur:"02:53",desc:"Acoustic Bachata, fingerstyle guitar, soft..."},
  {pos:572,title:"Bachata Morning V3",dur:"02:52",desc:"Ambient Bachata, atmospheric pads, shi..."},
  {pos:573,title:"November Breeze V3",dur:"02:34",desc:"Acoustic Bachata, fingerstyle guitar, soft..."},
  {pos:574,title:"Breeze and Brass",dur:"03:14",desc:"Orchestral Bachata, sweeping strings, w..."},
  {pos:575,title:"November Strings",dur:"02:49",desc:"Orchestral Bachata, sweeping strings, v..."},
  {pos:576,title:"Bachata Morning",dur:"03:11",desc:"Ambient Bachata, atmospheric pads, shi..."},
  {pos:577,title:"Sun in My Shade",dur:"03:49",desc:"Dominican Bachata, atmospheric guitar..."},
  {pos:578,title:"Melody I Can't Forget",dur:"04:02",desc:"Dominican Bachata, atmospheric guitar..."},
  {pos:579,title:"Sun in My Shade",dur:"03:34",desc:"Dominican Bachata, atmospheric guitar..."},
  {pos:580,title:"Melody I Can't Forget",dur:"03:26",desc:"Dominican Bachata, atmospheric guitar..."},
  {pos:581,title:"Sun in My Shade",dur:"03:38",desc:"Dominican Bachata, atmospheric guitar..."},
  {pos:582,title:"Melody I Can't Forget",dur:"03:27",desc:"Dominican Bachata, atmospheric guitar..."},
  {pos:583,title:"Sun in My Shade",dur:"03:46",desc:"Dominican Bachata, atmospheric guitar..."},
  {pos:584,title:"Melody I Can't Forget",dur:"03:47",desc:"Dominican Bachata, atmospheric guitar..."},
  {pos:585,title:"Summer's Last Dance",dur:"03:09",desc:"Kompa, driving bassline, layered percussi..."},
  {pos:586,title:"Ap Danse Nan Bra M",dur:"03:34",desc:"Kompa, driving bassline, layered percussi..."},
  {pos:587,title:"The Last Dance",dur:"03:14",desc:"Bachata, syncopated rhythm, bright requi..."},
  {pos:588,title:"Bailando en Mis Brazos",dur:"02:54",desc:"Bachata, syncopated rhythm, bright requi..."},
  {pos:589,title:"Bachata in the Shade",dur:"03:46",desc:"Dominican Bachata, atmospheric requint..."},
  {pos:590,title:"Rhythm That Holds Me True",dur:"03:01",desc:"Dominican Bachata, atmospheric requint..."},
  {pos:591,title:"Bachata in the Shade",dur:"03:44",desc:"Dominican Bachata, atmospheric guitar,..."},
  {pos:592,title:"Song That Won't Let Go",dur:"03:38",desc:"Dominican Bachata, atmospheric guitar,..."},
  {pos:593,title:"Love Beyond the Distance",dur:"03:59",desc:"Dominican Bachata, syncopated rhythm,..."},
  {pos:594,title:"Villa Waves and Bachata",dur:"03:44",desc:"Dominican Bachata, syncopated rhythm,..."},
  {pos:595,title:"Stitched with Light",dur:"03:24",desc:"acoustic bachata, twin fingerpicked guit..."},
  {pos:596,title:"Sunset Over Sosúa",dur:"03:31",desc:"bachata fusion, güira, tambora, warm ba..."},
  {pos:597,title:"Salt in the Air",dur:"03:31",desc:"bachata fusion, güira, tambora, warm ba..."},
  {pos:598,title:"Salt and Sun",dur:"03:21",desc:"merengue-bachata fusion, güira, tambor..."},
  {pos:599,title:"Hands of Home",dur:"03:21",desc:"merengue-bachata fusion, güira, tambor..."},
  {pos:600,title:"Stillness by the Sea",dur:"03:34",desc:"acoustic bachata, twin fingerpicked guit..."},
  {pos:601,title:"Hands That Build a Home",dur:"04:09",desc:"acoustic bachata, twin fingerpicked guit..."},
  {pos:602,title:"Peace We Didn't Know",dur:"03:43",desc:"modern bachata, güira, tambora, sweepi..."},
  {pos:603,title:"Hands That Build the Sun",dur:"03:47",desc:"modern bachata, güira, tambora, sweepi..."},
  {pos:604,title:"Hands That Build the Sun",dur:"03:12",desc:"modern bachata, güira, tambora, sweepi..."},
  {pos:605,title:"Heartbeat of the Island",dur:"03:26",desc:"merengue-bachata fusion, güira, tambor..."},
  {pos:606,title:"Morning Dew",dur:"03:39",desc:"acoustic bachata, twin fingerpicked nylo..."},
  {pos:607,title:"Holy Ground",dur:"03:32",desc:"acoustic bachata, twin fingerpicked nylo..."},
  {pos:608,title:"One True End",dur:"03:49",desc:"Cinematic Bachata, melodic nylon guitar..."},
  {pos:609,title:"Hold Your Head High",dur:"04:06",desc:"Cinematic Bachata, melodic nylon guitar..."},
  {pos:610,title:"Bachata for the Ones Who S...",dur:"03:33",desc:"bachata, bright melodic lead guitar, ag..."},
  {pos:611,title:"Mi Reina, Don't Cry",dur:"03:34",desc:"bachata, bright melodic lead guitar, ag..."},
  {pos:612,title:"Dancing Without Seasons",dur:"04:51",desc:"Cinematic Bachata, nylon guitar, sweepi..."},
  {pos:613,title:"Streetlights Bless Our Age",dur:"05:49",desc:"Cinematic Bachata, nylon guitar, sweepi..."},
  {pos:614,title:"Your Youth in Mine",dur:"04:08",desc:"romantic bachata, bright lead guitar, rhyt..."},
  {pos:615,title:"We Dance Where Time Aligns",dur:"04:31",desc:"romantic bachata, bright lead guitar, rhyt..."},
  {pos:616,title:"Winter Into Sound",dur:"04:58",desc:"cinematic bachata, nylon guitar, syncop..."},
  {pos:617,title:"Across the Line",dur:"04:58",desc:"cinematic bachata, nylon guitar, syncop..."},
  {pos:618,title:"Love Beyond Borders",dur:"03:19",desc:"acoustic bachata, fingerstyle nylon guita..."},
  {pos:619,title:"Dancing in My Arms",dur:"03:29",desc:"acoustic bachata, fingerstyle nylon guita..."},
  {pos:620,title:"Love Beyond Borders",dur:"03:34",desc:"pop-bachata fusion, rhythm guitar, ag..."},
  {pos:621,title:"Dancing in My Arms",dur:"03:57",desc:"pop-bachata fusion, rhythm guitar, ag..."},
  {pos:622,title:"Love Beyond Borders",dur:"04:41",desc:"romantic bachata, bright lead guitar, rhyt..."},
  {pos:623,title:"Dancing in My Arms",dur:"03:48",desc:"romantic bachata, bright lead guitar, rhyt..."},
  {pos:624,title:"Steps Through the Night",dur:"04:07",desc:"acoustic bachata, fingerstyle nylon guita..."},
  {pos:625,title:"Steps Through the Night",dur:"03:24",desc:"pop-bachata fusion, bright lead guitar, g..."},
  {pos:626,title:"Streetlights Hold Us Tight",dur:"03:41",desc:"pop-bachata fusion, bright lead guitar, g..."},
  {pos:627,title:"Heartbeats in the Dominica...",dur:"04:28",desc:"romantic bachata, bright lead guitar, güir..."},
  {pos:628,title:"We Dance Where Once I Wa...",dur:"03:52",desc:"romantic bachata, bright lead guitar, güir..."},
];

// Convert MM:SS duration string to total seconds
function durToSecs(durStr) {
  if (!durStr) return 0;
  const parts = String(durStr).trim().split(':');
  if (parts.length === 2) {
    return parseInt(parts[0], 10) * 60 + parseInt(parts[1], 10);
  }
  return 0;
}

// Build a lookup: title (normalized) -> array of {csvRow, durSecs}
function buildLookup() {
  const lookup = new Map();
  for (const row of CSV_ROWS) {
    const key = row.title.toLowerCase().trim();
    if (!lookup.has(key)) lookup.set(key, []);
    lookup.get(key).push({ row, durSecs: durToSecs(row.dur) });
  }
  return lookup;
}

// Find best CSV match for a Supabase song
function findMatch(songTitle, songDurSecs, lookup) {
  const normalTitle = songTitle.toLowerCase().trim();

  // 1. Exact match
  if (lookup.has(normalTitle)) {
    const candidates = lookup.get(normalTitle);
    if (candidates.length === 1) return candidates[0].row;
    // Multiple — pick closest duration
    return candidates.sort((a, b) => Math.abs(a.durSecs - songDurSecs) - Math.abs(b.durSecs - songDurSecs))[0].row;
  }

  // 2. Prefix match (CSV title ends with "..." — strip the dots and match as prefix)
  for (const [key, candidates] of lookup.entries()) {
    const csvTitleClean = key.replace(/\.+$/, '').trim();
    // CSV title is a prefix of the Supabase title
    if (csvTitleClean.length >= 8 && normalTitle.startsWith(csvTitleClean)) {
      if (candidates.length === 1) return candidates[0].row;
      return candidates.sort((a, b) => Math.abs(a.durSecs - songDurSecs) - Math.abs(b.durSecs - songDurSecs))[0].row;
    }
    // Supabase title is a prefix of the CSV title (less common)
    if (normalTitle.length >= 8 && csvTitleClean.startsWith(normalTitle)) {
      if (candidates.length === 1) return candidates[0].row;
      return candidates.sort((a, b) => Math.abs(a.durSecs - songDurSecs) - Math.abs(b.durSecs - songDurSecs))[0].row;
    }
  }

  return null;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    // Get Supabase connection
    const conn = await base44.asServiceRole.connectors.getConnection("supabase");
    const accessToken = conn?.accessToken;

    const keysRes = await fetch(`https://api.supabase.com/v1/projects/${PROJECT_REF}/api-keys`, {
      headers: { "Authorization": `Bearer ${accessToken}` }
    });
    const keys = await keysRes.json();
    const serviceKey = keys.find(k => k.name === 'service_role')?.api_key;
    if (!serviceKey) {
      return Response.json({ error: 'Could not get Supabase service key' }, { status: 500 });
    }

    const restHeaders = {
      "apikey": serviceKey,
      "Authorization": `Bearer ${serviceKey}`,
      "Content-Type": "application/json",
      "Prefer": "return=minimal"
    };

    // Fetch all songs from Supabase
    let allSongs = [];
    let offset = 0;
    const pageSize = 200;
    while (true) {
      const res = await fetch(
        `https://${PROJECT_REF}.supabase.co/rest/v1/songs?select=id,title,duration&order=id.asc&limit=${pageSize}&offset=${offset}`,
        { headers: restHeaders }
      );
      const page = await res.json();
      if (!Array.isArray(page) || page.length === 0) break;
      allSongs = allSongs.concat(page);
      if (page.length < pageSize) break;
      offset += pageSize;
    }

    console.log(`Fetched ${allSongs.length} songs from Supabase`);

    const lookup = buildLookup();
    const sleep = (ms) => new Promise(r => setTimeout(r, ms));

    let matched = 0;
    let notFound = [];
    let skipped = 0;

    for (const song of allSongs) {
      const songDurSecs = durToSecs(song.duration);
      const csvRow = findMatch(song.title, songDurSecs, lookup);

      if (!csvRow) {
        notFound.push({ title: song.title, duration: song.duration });
        continue;
      }

      const desc = csvRow.desc;
      if (!desc) {
        skipped++;
        continue;
      }

      // Update description in Supabase
      const updateRes = await fetch(
        `https://${PROJECT_REF}.supabase.co/rest/v1/songs?id=eq.${song.id}`,
        {
          method: 'PATCH',
          headers: restHeaders,
          body: JSON.stringify({ description: desc })
        }
      );

      if (updateRes.ok) {
        matched++;
        console.log(`Updated: "${song.title}" (pos ${csvRow.pos})`);
      } else {
        const errBody = await updateRes.text();
        console.error(`Failed to update "${song.title}": ${errBody}`);
        notFound.push({ title: song.title, duration: song.duration, error: errBody });
      }

      await sleep(50);
    }

    return Response.json({
      summary: {
        matched_and_updated: matched,
        not_found: notFound.length,
        skipped: skipped,
        total_supabase_songs: allSongs.length,
        total_csv_rows: CSV_ROWS.length,
      },
      not_found_list: notFound
    });

  } catch (err) {
    console.error('importDescriptionsFromCSV error:', err.message);
    return Response.json({ error: err.message }, { status: 500 });
  }
});